spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: none
  profiles:
    include:
      - db
  thymeleaf:
    prefix: classpath:/templates


